# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38e807855fb71cac59e3ed7fa67968e89384506bbf8b7e3ae0038dafce9aeddecb62900de252f6d488a2f3b84fe6606947f609de69bd43bc6bf4f46c72f30042

test:
  secret_key_base: 0e715f7c470cf55ad248d06f72e85f69d065714fa448274d8ea9706dc2ef030b1a98d2ca11a45e993049393dbc3b5dc6d23f3a037a8069a8e6f3b0e70c8397e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
